import chalk from "chalk";
import ora from "ora";
import { resolve } from "node:path";
import simpleGit from "simple-git";
import { FindingsStore, computeScore } from "../orchestrator/findingsStore.js";
import { runAudit } from "../orchestrator/bobRunner.js";
import { buildAuditPrompt } from "../orchestrator/promptBuilder.js";
import type { Framework, Finding, Severity } from "../types.js";

export interface WatchOptions {
  framework: Framework;
  path: string;
  base: string;
  format: "json" | "github-actions" | "markdown";
}

function makeFindingId(scanRunId: string, framework: Framework, control: string, file: string, line: number, idx: number): string {
  const runShort = scanRunId.replace(/[^a-z0-9]/gi, "").slice(-8);
  const slug = `${runShort}-${framework}-${control}-${file.replace(/[^a-z0-9]/gi, "_")}-${line}-${idx}`
    .toLowerCase()
    .slice(0, 120);
  return slug;
}

async function getDiffedFiles(cwd: string, base: string): Promise<string[]> {
  const git = simpleGit(cwd);
  
  // Check if base ref exists
  let targetBase = base;
  try {
    await git.revparse([base]);
  } catch {
    // Fallback to HEAD~1 if base doesn't exist
    try {
      await git.revparse(["HEAD~1"]);
      targetBase = "HEAD~1";
    } catch {
      // If even HEAD~1 doesn't exist, return empty (likely initial commit)
      return [];
    }
  }

  // Get diff between HEAD and base
  const diff = await git.diff([targetBase, "HEAD", "--name-only"]);
  const files = diff
    .split("\n")
    .map((f) => f.trim())
    .filter((f) => f.length > 0);

  // Filter to supported extensions (same as discoverFiles)
  const supportedExts = [
    ".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs",
    ".py", ".go", ".rb", ".java",
    ".sql", ".yaml", ".yml", ".json"
  ];

  return files.filter((f) => supportedExts.some((ext) => f.endsWith(ext)));
}

function formatGitHubActions(findings: Finding[]): string {
  const lines: string[] = [];
  
  for (const f of findings) {
    let level = "error";
    if (f.severity === "medium") level = "warning";
    if (f.severity === "low") level = "notice";
    
    const msg = `::${level} file=${f.file},line=${f.line_start},title=${f.control}::${f.explanation}`;
    lines.push(msg);
  }
  
  return lines.join("\n");
}

function formatMarkdown(args: {
  framework: Framework;
  findings: Finding[];
  score: number;
  source: "live" | "mock";
}): string {
  const counts: Record<Severity, number> = { critical: 0, high: 0, medium: 0, low: 0 };
  for (const f of args.findings) counts[f.severity]++;

  const lines: string[] = [];
  lines.push("<!-- sentinel-watch-comment -->");
  lines.push(`## 🛡️ Sentinel compliance report — \`${args.framework}\``);
  lines.push("");
  lines.push(`**Score:** \`${args.score} / 100\``);
  lines.push("");
  lines.push("| Severity | Count |");
  lines.push("|---|---|");
  lines.push(`| 🔴 critical | ${counts.critical} |`);
  lines.push(`| 🟠 high     | ${counts.high} |`);
  lines.push(`| 🟡 medium   | ${counts.medium} |`);
  lines.push(`| ⚪ low      | ${counts.low} |`);
  lines.push("");

  if (args.findings.length > 0) {
    lines.push("<details><summary>Findings</summary>");
    lines.push("");
    
    // Sort by severity
    const sorted = [...args.findings].sort((a, b) => {
      const order: Record<Severity, number> = { critical: 0, high: 1, medium: 2, low: 3 };
      return order[a.severity] - order[b.severity];
    });

    for (const f of sorted) {
      const emoji = f.severity === "critical" ? "🔴" : f.severity === "high" ? "🟠" : f.severity === "medium" ? "🟡" : "⚪";
      lines.push(`- ${emoji} **${f.severity.toUpperCase()}** — \`${f.control}\` [${f.file}:${f.line_start}](../blob/HEAD/${f.file}#L${f.line_start}) — ${f.explanation}`);
    }
    
    lines.push("");
    lines.push("</details>");
  } else {
    lines.push("✅ **No findings in changed files.**");
  }

  lines.push("");
  
  if (counts.critical > 0) {
    lines.push("❌ **This PR is blocked** — resolve all `critical`-severity findings before merging.");
    lines.push("");
    lines.push("Run `sentinel remediate --all --path .` locally to auto-generate fix patches.");
  } else if (counts.high > 0) {
    lines.push("⚠️ **High-severity findings detected** — review before merging.");
  } else {
    lines.push("✅ **No blocking findings.** Lower-severity items can be triaged separately.");
  }

  lines.push("");
  lines.push(`<sub>Generated by [Sentinel](https://github.com/vaatus/sentinel) · powered by IBM Bob · source: ${args.source}</sub>`);

  return lines.join("\n");
}

export async function runWatch(opts: WatchOptions): Promise<void> {
  const target = resolve(opts.path);
  const storeDir = target;
  const store = new FindingsStore(storeDir);

  const isJson = opts.format === "json";

  if (!isJson) {
    console.log();
    console.log(chalk.bold.cyan("  ┌──────────────────────────────────────────────┐"));
    console.log(chalk.bold.cyan("  │") + chalk.bold.white("   SENTINEL WATCH — Agentic Diff Scanner      ") + chalk.bold.cyan("│"));
    console.log(chalk.bold.cyan("  │") + chalk.dim("           powered by IBM Bob                 ") + chalk.bold.cyan("│"));
    console.log(chalk.bold.cyan("  └──────────────────────────────────────────────┘"));
    console.log();
    console.log(chalk.dim(`  Target:    `) + target);
    console.log(chalk.dim(`  Framework: `) + opts.framework.toUpperCase());
    console.log(chalk.dim(`  Base:      `) + opts.base);
    console.log();
  }

  const scanRun = store.createScanRun(opts.framework, target);
  const discoverSpin = isJson ? null : ora("Discovering changed files…").start();
  
  const diffedFiles = await getDiffedFiles(target, opts.base);
  
  if (diffedFiles.length === 0) {
    discoverSpin?.succeed("No changed files to scan");
    store.finalizeScanRun(scanRun.id, { totalFiles: 0, findingCount: 0, score: 100 });
    store.close();

    if (isJson) {
      process.stdout.write(
        JSON.stringify(
          {
            scan_id: scanRun.id,
            framework: opts.framework,
            score: 100,
            findings: [],
            summary: "No files changed",
            source: "n/a",
          },
          null,
          2,
        ),
      );
      process.stdout.write("\n");
    } else if (opts.format === "github-actions") {
      // No output for GitHub Actions if no findings
    } else if (opts.format === "markdown") {
      console.log(formatMarkdown({
        framework: opts.framework,
        findings: [],
        score: 100,
        source: "mock",
      }));
    }
    return;
  }

  discoverSpin?.succeed(`Discovered ${chalk.bold(diffedFiles.length)} changed files`);

  const auditSpin = isJson
    ? null
    : ora(`Invoking IBM Bob (${opts.framework}-auditor mode)…`).start();

  const auditPrompt = buildAuditPrompt(opts.framework, diffedFiles);
  const audit = await runAudit({
    framework: opts.framework,
    cwd: target,
    files: diffedFiles,
    prompt: auditPrompt,
  });

  auditSpin?.succeed(
    `Bob (${opts.framework}-auditor, ${audit.source}) returned ${chalk.bold(audit.json.findings.length)} findings across ${audit.json.scanned_files} files`,
  );

  const findings: Finding[] = audit.json.findings.map((f, i) => ({
    id: makeFindingId(scanRun.id, opts.framework, f.control, f.file, f.line_start, i),
    framework: opts.framework,
    control: f.control,
    control_name: f.control_name,
    file: f.file,
    line_start: f.line_start,
    line_end: f.line_end,
    code_snippet: f.code_snippet,
    severity: f.severity,
    explanation: f.explanation,
    remediation_hint: f.remediation_hint,
    status: "open",
    bob_session_id: audit.bobSessionId,
    created_at: new Date().toISOString(),
  }));

  store.insertFindings(scanRun.id, opts.framework, findings);

  const score = computeScore(findings);
  store.finalizeScanRun(scanRun.id, {
    totalFiles: audit.json.scanned_files,
    findingCount: findings.length,
    score,
  });
  const exportPath = store.exportToJson();
  store.close();

  // Output based on format
  if (opts.format === "json") {
    process.stdout.write(
      JSON.stringify(
        {
          scan_id: scanRun.id,
          framework: opts.framework,
          score,
          findings,
          summary: audit.json.summary,
          export: exportPath,
          bob_session_id: audit.bobSessionId,
          source: audit.source,
        },
        null,
        2,
      ),
    );
    process.stdout.write("\n");
  } else if (opts.format === "github-actions") {
    const output = formatGitHubActions(findings);
    if (output) {
      console.log(output);
    }
  } else if (opts.format === "markdown") {
    console.log(formatMarkdown({
      framework: opts.framework,
      findings,
      score,
      source: audit.source,
    }));
  }
}

// Made with Bob
